import { IBM_Plex_Sans_Thai } from 'next/font/google'
import FlyonuiScript from '@/core/flyonui/FlyonuiScript'
import type { Metadata } from 'next'
import './globals.css'

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  variable: '--font-ibm-plex-thai',
  subsets: ['thai', 'latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="th" className={`${ibmPlexSansThai.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <FlyonuiScript />
        {children}
      </body>
    </html>
  )
}
